fix(build config) refactor postbuild.js for fix error in app use uikit. Error TS2307: ... moduleResolution: but this result could not be resolved under your current moduleResolution setting. Consider updating to node16, nodenext, or bundler.