dev (#12)
* feat(InfiniteScrollWrapper) added new component InfiniteScrollWrapper.tsx for use infinite scroll when user scroll in down.

* fix(Circle canvas) refactor JSDoc in CircleCanvas.tsx added description monthMarker prop.

* fix(global css) added new styles

* feat(new file upload) added new component FileUpload.tsx. all functional

* fix(type) in FileUpload.tsx

* feat(hook) added and use custom hook useFileUpload.ts for FileUpload.tsx component

* feat(hook) added and use custom hook useCircleCanvas.ts.ts for CircleCanvas.tsx.tsx component

* fix(hook or types) added and use custom hook useFileUpload.ts for FileUpload.tsx component

* feat(hook or types) added and use custom hook useInfiniteScrollWrapper.ts for InfiniteScrollWrapper.tsx component

* fix(build files) refactor build files postbuild.js and tsconfig.build.json for optimize build project

* fix(build config) refactor postbuild.js for fix error in app use uikit. Error TS2307: ... moduleResolution: but this result could not be resolved under your current moduleResolution setting. Consider updating to node16, nodenext, or bundler.

* fix(JSDoc) refactor documentation in all components.